# Generated by Django 4.2.28 on 2026-02-05 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Cache',
                'verbose_name_plural': 'Analytics Cache',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('widget_type', models.CharField(choices=[('counter', "Counter - Raqam ko'rsatkich"), ('pie_chart', 'Pie Chart - Doira diagramma'), ('bar_chart', 'Bar Chart - Ustun diagramma'), ('line_chart', 'Line Chart - Chiziqli grafik'), ('table', 'Table - Jadval'), ('progress', 'Progress Bar - Progress'), ('stat_card', 'Stat Card - Statistika karta')], max_length=20, verbose_name='Widget turi')),
                ('data_source', models.CharField(help_text='API endpoint yoki funksiya nomi', max_length=100, verbose_name="Ma'lumot manbasi")),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Sozlamalar')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('visible_to_superadmin', models.BooleanField(default=True, verbose_name="SuperAdmin ko'radi")),
                ('visible_to_admin', models.BooleanField(default=True, verbose_name="Admin ko'radi")),
                ('visible_to_teacher', models.BooleanField(default=False, verbose_name="O'qituvchi ko'radi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('report_type', models.CharField(choices=[('portfolio_summary', 'Portfolio Summary'), ('assignment_summary', 'Assignment Summary'), ('teacher_performance', 'Teacher Performance'), ('category_analytics', 'Category Analytics'), ('monthly_report', 'Monthly Report'), ('yearly_report', 'Yearly Report'), ('custom_report', 'Custom Report')], default='custom_report', max_length=50, verbose_name='Hisobot turi')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='json', max_length=10, verbose_name='Format')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filterlar')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name="Ma'lumotlar")),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Fayl')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Fayl hajmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('error_message', models.TextField(blank=True, verbose_name='Xatolik xabari')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Hisobot',
                'verbose_name_plural': 'Hisobotlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
