# Generated by Django 4.2.28 on 2026-02-05 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.PositiveIntegerField(default=1, verbose_name='required quantity')),
                ('completed_quantity', models.PositiveIntegerField(default=0, verbose_name='completed quantity')),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Additional instructions for the teacher', null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='priority')),
                ('use_custom_score', models.BooleanField(default=False, help_text="True bo'lsa, kategoriya default balini emas, maxsus ballni ishlatadi", verbose_name='use custom score')),
                ('custom_max_score', models.PositiveIntegerField(blank=True, help_text='Maxsus maksimal ball (masalan: oddiy esse=10, kuchli esse=20)', null=True, verbose_name='custom maximum score')),
                ('custom_min_score', models.PositiveIntegerField(blank=True, default=0, help_text='Maxsus minimal ball', null=True, verbose_name='custom minimum score')),
                ('score_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Ball koeffitsienti (1.0=normal, 1.5=50% bonus, 2.0=2x ball)', max_digits=4, verbose_name='score multiplier')),
                ('score_note', models.CharField(blank=True, help_text='Ball o\'zgartirilgan sababi (masalan: "Ilmiy jurnal uchun bonus")', max_length=255, null=True, verbose_name='score note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('counted', models.BooleanField(default=False, help_text='Whether this progress counts towards the assignment', verbose_name='counted')),
                ('raw_score', models.PositiveIntegerField(blank=True, help_text='Baholangan ball (0 dan max_score gacha)', null=True, verbose_name='raw score')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text="Og'irlik bilan hisoblangan yakuniy ball", max_digits=8, null=True, verbose_name='final score')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='graded at')),
                ('grade_note', models.TextField(blank=True, help_text='Baholash haqida izoh', null=True, verbose_name='grade note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_progress', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_progress', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'assignment progress',
                'verbose_name_plural': 'assignment progress items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('score_set', "Ball o'rnatildi"), ('score_changed', "Ball o'zgartirildi"), ('custom_score_enabled', 'Maxsus ball yoqildi'), ('custom_score_disabled', "Maxsus ball o'chirildi"), ('multiplier_changed', "Koeffitsient o'zgartirildi")], max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='assignments.assignment')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_changes', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='assignments.assignmentprogress')),
            ],
            options={
                'verbose_name': 'score history',
                'verbose_name_plural': 'score histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='name (Uzbek)')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='name (Russian)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='name (English)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Icon class name (e.g., fa-file-text)', max_length=50, null=True, verbose_name='icon')),
                ('color', models.CharField(default='#3498db', help_text='Hex color code', max_length=20, verbose_name='color')),
                ('default_score', models.PositiveIntegerField(default=10, help_text='Bu kategoriya uchun standart maksimal ball (masalan: Esse=10, Tezis=15)', verbose_name='default score')),
                ('min_score', models.PositiveIntegerField(default=0, help_text='Minimal ball (odatda 0)', verbose_name='minimum score')),
                ('score_weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Ball koeffitsienti (1.0=100%, 1.5=150% bonus)', max_digits=4, verbose_name='score weight')),
                ('points', models.PositiveIntegerField(default=1, help_text='Points awarded for completing one item of this category', verbose_name='points')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assignments.category'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['teacher', 'status'], name='assignments_teacher_ddf333_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['deadline'], name='assignments_deadlin_85f71e_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['category'], name='assignments_categor_379ecf_idx'),
        ),
    ]
