# Generated by Django 4.2.28 on 2026-02-05 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(choices=[('teaching', 'Teaching Materials'), ('research', 'Research & Publications'), ('certificates', 'Certificates & Awards'), ('projects', 'Projects'), ('professional', 'Professional Development'), ('other', 'Other')], db_index=True, default='other', max_length=50, verbose_name='category')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='review comment')),
                ('meta_data', models.JSONField(blank=True, default=dict, help_text='Additional information like attachments, links, notes', null=True, verbose_name='metadata')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this portfolio is visible to everyone', verbose_name='is public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_portfolios', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'portfolio history',
                'verbose_name_plural': 'portfolio histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='portfolios.portfoliocomment')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'portfolio comment',
                'verbose_name_plural': 'portfolio comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='portfolio_attachments/%Y/%m/', verbose_name='file')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=20, verbose_name='file type')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes', verbose_name='file size')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'portfolio attachment',
                'verbose_name_plural': 'portfolio attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['status'], name='portfolios__status_94dff8_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['teacher'], name='portfolios__teacher_7fb96b_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['category'], name='portfolios__categor_a38c18_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['created_at'], name='portfolios__created_47bc52_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['status', 'teacher'], name='portfolios__status_20ec37_idx'),
        ),
    ]
