export { default as MainLayout } from './MainLayout.vue'
export { default as AuthLayout } from './AuthLayout.vue'
export { default as TeacherLayout } from './TeacherLayout.vue'
export { default as AdminLayout } from './AdminLayout.vue'
export { default as SuperAdminLayout } from './SuperAdminLayout.vue'
